[package]
name = "makero"
version = "0.1.0"
edition = "2018"
authors = ["tjjfvi"]
repository = "https://github.com/tjjfvi/makero"
license = "MIT"
keywords = ["macro", "macro_rules"]
categories = []

[dependencies]
